#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global

yabai -m config window_shadow                  on
yabai -m config window_opacity                 off
yabai -m config window_opacity_duration        0.0
yabai -m config active_window_opacity          1.0
yabai -m config normal_window_opacity          0.90
yabai -m config window_border                  off
yabai -m config window_border_width            6
yabai -m config active_window_border_color     0xff775759
yabai -m config normal_window_border_color     0xff555555
yabai -m config insert_feedback_color          0xffd75f5f

# general space settings
yabai -m config layout                         bsp
yabai -m config top_padding                    0
yabai -m config bottom_padding                 0
yabai -m config left_padding                   0
yabai -m config right_padding                  0
yabai -m config window_gap                     4


# apps to not manage (ignore)
yabai -m rule --add app="^System Preferences$" manage=off

echo "yabai configuration loaded.."

