# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

toggle_key: CTRL

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":nuget"
    replace: "https://api.nuget.org/v3/index.json"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"
          
  - trigger: ":tday"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":dn"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "[[%Y-%m-%d]]"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Breadcrumb
  - trigger: ":sc"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: 'echo `date -v -1d "+[[%Y-%m-%d|<< Yesterday]]"`'' | ''`date -v +1d "+[[%Y-%m-%d|Tommorrow >>]]"`'


    # Breadcrumb Windows
  - trigger: ":bc"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: (echo "[[$((Get-Date).AddDays(-1) | Get-Date -UFormat "%Y-%m-%d")|<< Yesterday]] | [[$((Get-Date).AddDays(+1) | Get-Date -UFormat "%Y-%m-%d")|Tomorrow >>]]")

  - trigger: ":42"
    replace: "4242 4242 4242 4242"


