#!/usr/bin/env sh
# focus window
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# swap managed window
shift + alt - h : yabai -m window --swap west
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - l : yabai -m window --swap east

# focus desktop
shift + alt - 1 :  yabai -m space --focus 1
shift + alt - 2 :  yabai -m space --focus 2
shift + alt - 3 :  yabai -m space --focus 3
shift + alt - 4 :  yabai -m space --focus 4
shift + alt - 5 :  yabai -m space --focus 5
shift + alt - 6 :  yabai -m space --focus 6
shift + alt - 7 :  yabai -m space --focus 7
shift + alt - 8 :  yabai -m space --focus 8
shift + alt - 9 :  yabai -m space --focus 9

# Move focus container to workspace
ctrl + alt - m : yabai -m window --space last; yabai -m space --focus last
ctrl + alt - p : yabai -m window --space prev; yabai -m space --focus prev
ctrl + alt - n : yabai -m window --space next; yabai -m space --focus next
ctrl + alt - 1 : yabai -m window --space 1; yabai -m space --focus 1
ctrl + alt - 2 : yabai -m window --space 2; yabai -m space --focus 2
ctrl + alt - 3 : yabai -m window --space 3; yabai -m space --focus 3
ctrl + alt - 4 : yabai -m window --space 4; yabai -m space --focus 4

# Resize windows
ctrl + alt - h : yabai -m window --resize left:-50:0; \
                  yabai -m window --resize right:-50:0
ctrl + alt - j : yabai -m window --resize bottom:0:50; \
                  yabai -m window --resize top:0:50
ctrl + alt - k : yabai -m window --resize top:0:-50; \
                  yabai -m window --resize bottom:0:-50
ctrl + alt - l : yabai -m window --resize right:50:0; \
                  yabai -m window --resize left:50:0

# Equalize size of windows
ctrl + alt - e : yabai -m space --balance

# Rotate windows clockwise and anticlockwise
alt - r         : yabai -m space --rotate 270
shift + alt - r : yabai -m space --rotate 90

# Focus next space by mission-control index if one exists, otherwise focus the first space
shift + alt - n : yabai -m space --focus next || yabai -m space --focus first

# Focus previous space by mission-control index if one exists, otherwise focus the last space
shift + alt - p : yabai -m space --focus prev || yabai -m space --focus last

# Make window native fullscreen
alt - f : yabai -m window --toggle zoom-fullscreen
shift + alt - f : yabai -m window --toggle native-fullscreen


# Restart Yabai
shift + ctrl + alt - r : \
    /usr/bin/env osascript <<< \
        "display notification \"Restarting Yabai\" with title \"Yabai\""; \
    launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

